"""add slug to products tables

Revision ID: f9c2f0462ab9
Revises: 8a3fde54fa59
Create Date: 2025-12-02 14:54:37.933946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c2f0462ab9'
down_revision: Union[str, Sequence[str], None] = '8a3fde54fa59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_hierarchy', sa.Column('category_slug', sa.String(), nullable=False))
    op.add_column('product_hierarchy', sa.Column('subcategory_slug', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_hierarchy', 'subcategory_slug')
    op.drop_column('product_hierarchy', 'category_slug')
    # ### end Alembic commands ###
