services:

  shopping-assistant:
    build:
      target: dev
    image: shopping-assistant:dev
    volumes:
      - ${REPO_ROOT}/services/shopping-assistant:/project/service
      - ${REPO_ROOT}/packages/shopping-assistant:/project/packages/shopping-assistant


  ecom-backend:
    build:
      target: dev
    image: ecom-backend:dev
    volumes:
      - ${REPO_ROOT}/services/ecom-backend:/project/service