services:

  chatbot:
    build:
      target: dev
    image: shopping-assistant-chatbot:dev
    volumes:
      - ${REPO_ROOT}/services/chatbot:/project/service
      - ${REPO_ROOT}/packages/chatbot:/project/packages/chatbot


  ecom-backend:
    build:
      target: dev
    image: ecom-backend:dev
    volumes:
      - ${REPO_ROOT}/services/ecom-backend:/project/service