name: Main workflow


on:
  push:
    branches:
      - "**"


env:
  PYTHON_VERSION: "3.12"


jobs:
  
  run_checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        run: uv python install ${{ env.PYTHON_VERSION }}

      - name: Setup code quality env
        run: |
          make venv-create COMPONENT=root GROUP=ci
          make venv-switch COMPONENT=root GROUP=ci

      - name: Run code quality checks
        run: make SKIP=no-commit-to-branch check-all
